<?php

namespace ContainerOuMxPaJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7XPcrkQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7XPcrkQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7XPcrkQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'annonce' => ['privates', '.errored..service_locator.7XPcrkQ.App\\Entity\\Annonce', NULL, 'Cannot autowire service ".service_locator.7XPcrkQ": it needs an instance of "App\\Entity\\Annonce" but this type has been excluded in "config/services.yaml".'],
            'annonceRepository' => ['privates', 'App\\Repository\\AnnonceRepository', 'getAnnonceRepositoryService', true],
        ], [
            'annonce' => 'App\\Entity\\Annonce',
            'annonceRepository' => 'App\\Repository\\AnnonceRepository',
        ]);
    }
}
