<?php

namespace ContainerOuMxPaJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getListAnnonceComponentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Twig\Components\ListAnnonceComponent' autowired service.
     *
     * @return \App\Twig\Components\ListAnnonceComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Twig/Components/ListAnnonceComponent.php';

        $container->factories['service_container']['App\\Twig\\Components\\ListAnnonceComponent'] = function () use ($container) {
            return new \App\Twig\Components\ListAnnonceComponent();
        };

        return $container->factories['service_container']['App\\Twig\\Components\\ListAnnonceComponent']();
    }
}
