<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_annonce_index' => [[], ['_controller' => 'App\\Controller\\AnnonceController::index'], [], [['text', '/annonce/']], [], [], []],
    'app_annonce_new' => [[], ['_controller' => 'App\\Controller\\AnnonceController::new'], [], [['text', '/annonce/new']], [], [], []],
    'app_annonce_show' => [['id'], ['_controller' => 'App\\Controller\\AnnonceController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/annonce']], [], [], []],
    'app_annonce_edit' => [['id'], ['_controller' => 'App\\Controller\\AnnonceController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/annonce']], [], [], []],
    'app_annonce_delete' => [['id'], ['_controller' => 'App\\Controller\\AnnonceController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/annonce']], [], [], []],
];
